/* XPM */
/*
static char * plot_icon[] = {
"48 48 4 1",
" 	c #FFFFFFFFFFFF",
".	c #000000000000",
"X	c #00000000FFFF",
"o	c #FFFF00000000",
"                                                ",
"     ..                                         ",
"     .  .................................       ",
"     .. .                               .       ",
"        .               .               .       ",
"        ..                              .       ",
"        .               .               .       ",
"     .. .                               .       ",
"     .. ...             .               .       ",
"      . .    XX                    XX   .       ",
" . .    .   X  X        .         X  X o.       ",
" . .    .. X    X                X   oo .       ",
"  .     .  X    X       .        X  o X .       ",
"  .  .. . X      X              X  o   X.       ",
"      . ..X      X      .       X o    X.       ",
"      . . X      X              oo     X.       ",
"        .X        X     .      o        .       ",
"        .X        X           oX        .       ",
"     .. .X        X     .    o X        .       ",
"     .. X          X       oo X         .       ",
"      . ... . . . .X. . . o . X . . . . .       ",
"        .          X     o    X         .       ",
"        .           X  oo    X          .       ",
"        ..          X o      X          .       ",
"        .            o  .    X          .       ",
"     .. .          oo       X           .       ",
"      . ..        o  X  .   X.........  .       ",
"     .. .        o   X      X.       .  .       ",
"        .      oo     X .  X . X ... .. .       ",
"        ..    o       X    X .       .. .       ",
"        .    o         X. X  .       .. .       ",
"     .. .  oo           XX   . o ... .. .       ",
"      . ..o             .    .       .. .       ",
"      . .o                   .......... .       ",
"        .               .      ........ .       ",
"        ..                              .       ",
"        .   .   .   .   .   .   .   .   .       ",
"     .  . . . . . . . . . . . . . . . . .       ",
"    . . .................................       ",
"     .                                          ",
"        .   .   ..  ..  ..  .   .   .   .       ",
"       . .  .   ..  ..  .   .  ..   .  ..       ",
"        .   .   .    .   .  .  ...  .   .       ",
"                                                ",
"                       . .                      ",
"                        .                       ",
"                       . .                      ",
"                                                "};
*/

/* XPM */
static char * plot_icon2[] = {
"48 48 5 1",
" 	c #FFFFFFFFFFFF",
".	c #000000000000",
"X	c #00000000FFFF",
"o	c #FFFF00000000",
"O	c #0000FFFFFFFF",
"                                                ",
"     ..                                         ",
"     .  .................................       ",
"     .. .                  ..           .       ",
"        .               . ...           .       ",
"        ..               ...            .       ",
"        .               ...             .       ",
"     .. .       ....   ...              .       ",
"     .. ...   ..X   .....               .       ",
"      . .    .   X    ..           XX   .       ",
" . .    .   X.    X   ...         X  X o.       ",
" . .    .. X.     X    .         X   oo .       ",
"  .     .  X. O    X   ..        X  o X .       ",
"  .  .. . X . OO   X   .        X  o   X.       ",
"      . ..X .  O   X   ..       X o    X.       ",
"      . . X .  OO   X  .        oo     X.       ",
"        .X   .  OO  X . .      o        .       ",
"        .X   .      X .       oX        .       ",
"     .. .X    ..    ..  .    o X        .       ",
"     .. X       ....       oo X         .       ",
"      . ... . . . .X. . . o . X . . . . .       ",
"        .          X     o    X         .       ",
"        .           X  oo    X          .       ",
"        ..          X o      X          .       ",
"        .            o  .    X          .       ",
"     .. .          oo       X           .       ",
"      . ..        o  X  .   X.........  .       ",
"     .. .        o   X      X.       .  .       ",
"        .      oo     X .  X . X ... .. .       ",
"        ..    o       X    X .       .. .       ",
"        .    o         X. X  .       .. .       ",
"     .. .  oo           XX   . o ... .. .       ",
"      . ..o             .    .       .. .       ",
"      . .o                   .......... .       ",
"        .               .      ........ .       ",
"        ..                              .       ",
"        .   .   .   .   .   .   .   .   .       ",
"     .  . . . . . . . . . . . . . . . . .       ",
"    . . .................................       ",
"     .                                          ",
"        .   .   ..  ..  ..  .   .   .   .       ",
"       . .  .   ..  ..  .   .  ..   .  ..       ",
"        .   .   .    .   .  .  ...  .   .       ",
"                                                ",
"                       . .                      ",
"                        .                       ",
"                       . .                      ",
"                                                "};
/* XPM */
/*
static char * sheet_icon[] = {
"48 48 3 1",
" 	c #FFFFFFFFFFFF",
".	c #000000000000",
"X	c #D6D6D6D6D6D6",
"                                                ",
"   ...........................................  ",
"   .XXXXXXXXXXXXX.XXXXXXXXXXXXX.XXXXXXXXXXXXX.  ",
"   .XXXXXXXXXXXXX.XXXXX...XXXXX.XXXX....XXXXX.  ",
"   .XXXXXXXXXXXXX.XXXX.XXX.XXXX.XXXX.XXX.XXXX.  ",
"   .XXXXXXXXXXXXX.XXXX.....XXXX.XXXX....XXXXX.  ",
"   .XXXXXXXXXXXXX.XXXX.XXX.XXXX.XXXX.XXX.XXXX.  ",
"   .XXXXXXXXXXXXX.XXXX.XXX.XXXX.XXXX....XXXXX.  ",
"   .XXXXXXXXXXXXX.XXXXXXXXXXXXX.XXXXXXXXXXXXX.  ",
"   ...........................................  ",
"   .XXXXXXXXXXXXX.             .             .  ",
"   .XXXXXX.XXXXXX.             .             .  ",
"   .XXXXXX.XXXXXX.             .             .  ",
"   .XXXXXX.XXXXXX.             .             .  ",
"   .XXXXXX.XXXXXX.             .             .  ",
"   .XXXXXXXXXXXXX.             .             .  ",
"   ...........................................  ",
"   .XXXXXXXXXXXXX.             .             .  ",
"   .XXXXX....XXXX.             .             .  ",
"   .XXXXXXX..XXXX.             .             .  ",
"   .XXXXX..XXXXXX.             .             .  ",
"   .XXXXX....XXXX.             .             .  ",
"   .XXXXXXXXXXXXX.             .             .  ",
"   ...........................................  ",
"   .XXXXXXXXXXXXX.             .             .  ",
"   .XXXXX....XXXX.             .             .  ",
"   .XXXXXX..XXXXX.             .             .  ",
"   .XXXXXXXX.XXXX.             .             .  ",
"   .XXXXX....XXXX.             .             .  ",
"   .XXXXXXXXXXXXX.             .             .  ",
"   ...........................................  ",
"   .XXXXXXXXXXXXX.             .             .  ",
"   .XXXXX.XX.XXXX.             .             .  ",
"   .XXXXX....XXXX.             .             .  ",
"   .XXXXXXXX.XXXX.             .             .  ",
"   .XXXXXXXX.XXXX.             .             .  ",
"   .XXXXXXXXXXXXX.             .             .  ",
"   ...........................................  ",
"   .XXXXXXXXXXXXX.             .             .  ",
"   .XXXXX....XXXX.             .             .  ",
"   .XXXXX...XXXXX.             .             .  ",
"   .XXXXXXXX.XXXX.             .             .  ",
"   .XXXXX....XXXX.             .             .  ",
"   .XXXXXXXXXXXXX.             .             .  ",
"   ...........................................  ",
"                                                ",
"                                                ",
"                                                "};
*/

/* XPM */
static char * sheet_icon2[] = {
"48 48 9 1",
" 	c #FFFFFFFFFFFF",
".	c #000000000000",
"X	c #D6D6D6D6D6D6",
"o	c #FFFF00000000",
"O	c #FFFF5E5EF3F3",
"+	c #FFFF0000FFFF",
"@	c #0000FFFFFFFF",
"#	c #FFFF91915555",
"$	c #FFFFFFFF0000",
"                                                ",
"   ...........................................  ",
"   .XXXXXXXXXXXXX.XXXXXXXXXXXXX.XXXXXXXXXXXXX.  ",
"   .XXXXXXXXXXXXX.XXXXX...XXXXX.XXXX....XXXXX.  ",
"   .XXXXXXXXXXXXX.XXXX.XXX.XXXX.XXXX.XXX.XXXX.  ",
"   .XXXXXXXXXXXXX.XXXX.....XXXX.XXXX....XXXXX.  ",
"   .XXXXXXXXXXXXX.XXXX.XXX.XXXX.XXXX.XXX.XXXX.  ",
"   .XXXXXXXXXXXXX.XXXX.XXX.XXXX.XXXX....XXXXX.  ",
"   .XXXXXXXXXXXXX.XXXXXXXXXXXXX.XXXXXXXXXXXXX.  ",
"   ...........................................  ",
"   .XXXXXXXXXXXXX.             .             .  ",
"   .XXXXXX.XXXXXX.             .   ...       .  ",
"   .XXXXXX.XXXXXX.      oo     .  .OO+.      .  ",
"   .XXXXXX.XXXXXX.    oooooo   .  ...O.      .  ",
"   .XXXXXX.XXXXXX.      oo     . .@@@..      .  ",
"   .XXXXXXXXXXXXX.             . ...@@.      .  ",
"   ..............................###.@........  ",
"   .XXXXXXXXXXXXX.             ..####.       .  ",
"   .XXXXX....XXXX.             .####.        .  ",
"   .XXXXXXX..XXXX.    oooooo   .####.        .  ",
"   .XXXXX..XXXXXX.            .####.         .  ",
"   .XXXXX....XXXX.            .####.         .  ",
"   .XXXXXXXXXXXXX.           .####.          .  ",
"   ...........................####............  ",
"   .XXXXXXXXXXXXX.          .####.           .  ",
"   .XXXXX....XXXX.          .####.     oo    .  ",
"   .XXXXXX..XXXXX.         .####.     oo     .  ",
"   .XXXXXXXX.XXXX.         .####.    oo      .  ",
"   .XXXXX....XXXX.        .####.    oo       .  ",
"   .XXXXXXXXXXXXX.        .####.             .  ",
"   .......................####................  ",
"   .XXXXXXXXXXXXX.       .####..             .  ",
"   .XXXXX.XX.XXXX.      .####. .   oo   oo   .  ",
"   .XXXXX....XXXX.      .####. .     ooo     .  ",
"   .XXXXXXXX.XXXX.     .####.  .     ooo     .  ",
"   .XXXXXXXX.XXXX.     .####.  .   oo   oo   .  ",
"   .XXXXXXXXXXXXX.    ...##.   .             .  ",
"   ....................$$.#...................  ",
"   .XXXXXXXXXXXXX.    .$$$.    .             .  ",
"   .XXXXX....XXXX.    ..$..    .   ooooooo   .  ",
"   .XXXXX...XXXXX.    ...      .             .  ",
"   .XXXXXXXX.XXXX.    .        .   ooooooo   .  ",
"   .XXXXX....XXXX.             .             .  ",
"   .XXXXXXXXXXXXX.             .             .  ",
"   ...........................................  ",
"                                                ",
"                                                ",
"                                                "};
