#!/bin/sh


copyright_gtkextra ()
{
  cat << EOF
/* GTK+Extra - Library of useful widgets for programming with GTK+ 
 * Copyright (C) 1999-2001 Adrian E. Feiguin
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the 
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA  02111-1307, USA.
 */
EOF
}

for file in `find . -name "*.[ch]" -print`; do
  exclude=`echo $exclude_files | grep $file`

  if test "x$exclude" = "x"; then
    dir=`dirname $file`
    if test "x$dir" != "x."; then
      subdir=`basename $dir`

      grepout=`grep Copyright $file`
      if test "x$grepout" = "x"; then
        backup_dir="$dir/bak"
        if test ! -d $backup_dir; then
          echo "making directory: $backup_dir"
          mkdir $backup_dir
        fi

        echo $file

        filename=`basename $file`
        cp $file $backup_dir/$filename
        copyright_$subdir > $file
        cat $backup_dir/$filename >> $file
      fi
    fi
  fi
done
